---
title: "census_pulse_lgbtq"
author: "suzanne"
date: "2023-05-15"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(openxlsx)
library(dplyr)
library(data.table)
library(janitor)
library(tidyr)
library(psrcplot)
library(ggplot2)
library(echarts4r)
```



```{r cars}
#where you want your outputs to go
dest_file_loc <-
  "C:/GitHub/equity-focused-trends/pride/census_pulse"

#the same for all data tables
url_start <-
  'https://www2.census.gov/programs-surveys/demo/tables/hhp/'

#which weeks to summarize
week_range <- 34:57

sheet_name <- 'Seattle_Metro_Area'
```


### Population summary; for averaging over weeks
```{r, echo=FALSE, message=FALSE, warning=FALSE}

tbl<-'employ1'
df_people<-data.frame()
df_sexorient<-data.frame()

for (week in week_range) {
  # have to assign which year each week was in to make the url
  if (week < 42) {
    year = '2021'
  }
  else if (week < 52)
  {
    year = '2022'
  }
  else{
    year = '2023'

  }
  week_char <- as.character(week)

  url_end <-
      paste0(year,'/','wk',week_char,'/',tbl,
             '_week',week_char,'.xlsx')
    url <- paste0(url_start, url_end)
    file_end <- gsub('/', '_', url_end)
    dest_file = paste0(dest_file_loc, file_end)

    df <- read.xlsx(url, sheet = sheet_name, fillMergedCells = TRUE)

    df_row23_28<- df %>% slice(23:28)
    df_detail <- df_row23_28 %>% select(1:2)
    df_detail  <-  df_detail %>% rename('SexualOrientation'= 1,
                                        'total' = 2)%>%
                                 mutate(week=week)
      
    df_row30_33<- df %>% slice(30:33)
    #df_row32_34<-df%>%slice(32:34)
    df_lgbtq <- df_row30_33 %>% select(1:2)
    df_lgbtq <- df_lgbtq %>% rename('LGBT'= 1,
                                            'total' = 2)%>%
    mutate(week=week)

    #bind the weeks together
    df_people <- rbind(df_people, df_lgbtq)
    df_sexorient<- rbind(df_sexorient,df_detail)
}

```
```{r}
df_people_1<-df_people%>%group_by(week)%>%
  mutate(LGBT_grp= case_match(LGBT,
         "    Yes" ~"LGBT identifying",
         "    No" ~"Not LGBT identifying",
         "    Other" ~"Other",
         "    Did not report" ~"Did not report"))%>%drop_na()%>%
  mutate(
           rounded_total=round(as.numeric(total), -3)
         )%>%mutate(share=as.numeric(total)/sum(as.numeric(total)))

week_est<-df_people_1 |> group_by(LGBT_grp)|>
  e_charts(week) |>
  e_line(share) |>
  e_title("Sexual Orientation Estimated by Week (Census Pulse weeks)")|>
  e_x_axis(week) |>
  e_legend(bottom=0)|>
  e_y_axis(
    formatter = e_axis_formatter("percent", digits = 0)
  )

week_est
```

```{r}
LGBT_mean<-df_people%>%group_by(LGBT)%>%
  summarize('population'=mean(as.numeric(total)))%>%
  mutate(LGBT_grp= case_match(LGBT,
         "    Yes" ~"LGBT identifying",
         "    No" ~"Not LGBT identifying",
         "    Other" ~"Other",
         "    Did not report" ~"Did not report"))%>%drop_na()%>%
  mutate(
           rounded_pop=round(population, -3)
         )%>%mutate(share=population/sum(population))

sex_ort_mean<-df_sexorient%>%group_by(SexualOrientation)%>%
  summarize('population'=mean(as.numeric(total)))%>%
              mutate(rounded_pop=round(population, -3))%>%drop_na()

```

```{r}
static_bar_chart(LGBT_mean, x= 'share', y='LGBT_grp', fill='LGBT_grp')

LGBT_mean |>
  e_charts(LGBT_grp) |>
  e_bar(share)|>
  e_legend(FALSE) |>
  e_theme("infographic")|>
  e_y_axis(
    formatter = e_axis_formatter("percent", digits = 0)
  )
    
```
```{r}
static_bar_chart(sex_ort_mean, x= 'rounded_pop', y='SexualOrientation', fill='SexualOrientation')

sex_ort_mean |>
  e_charts(SexualOrientation) |>
  e_bar(rounded_pop, hideOverlap = TRUE)|>
  e_legend(FALSE) |>
  e_theme("infographic")
```

### Anxiety data download
```{r, echo=FALSE, message=FALSE, warning=FALSE}

#which weeks to summarize
week_range <- 34:57

sheet_name <- 'Seattle_Metro_Area'

df_anxiety<-data.frame()

for (week in week_range) {
  # have to assign which year each week was in to make the url
  if (week < 42) {
    year = '2021'
    #they changed the table names over time, ugh!!
    tbl <- 'health2a'
  }
  else if (week < 52)
  {
    year = '2022'
    # this is stupid
    if (week < 49) {
      tbl <- 'health2a'
    }
    else{
      tbl <- 'health1'
    }
  }
  else{
    year = '2023'
    tbl <- 'health1'
  }
  week_char <- as.character(week)

    url_end <-
      paste0(year,'/','wk',week_char,'/',tbl,
             '_week',week_char,'.xlsx')
    url <- paste0(url_start, url_end)
    file_end <- gsub('/', '_', url_end)
    dest_file = paste0(dest_file_loc, file_end)

    df <- read.xlsx(url, sheet = sheet_name, fillMergedCells = TRUE)
    df_row5 <- df %>% slice(5)
    df_row32_35<- df %>% slice(32:35)
    #df_row32_34<-df%>%slice(32:34)
    df_lgbtq <- bind_rows(df_row5, df_row32_35) %>% select(1:6)
    df_lgbtq <- df_lgbtq %>% row_to_names(row_number = 1)
    #rows 5 in the 25-30 position 32-34 position
    df_lgbtq[df_lgbtq=="-"] <- "0"
    
    df_lgbtq_summ <-
      df_lgbtq%>% pivot_longer(
        cols = c(
          'Not at all',
          'Several days',
          'More than half the days',
          'Nearly every day',
          'Did not report'
        ),
        names_to = 'anxiety_freq',
        values_to = 'total'
      ) %>%
      filter(anxiety_freq != 'Did not report') %>%
      mutate(
        anxiety_grp = case_when(
          anxiety_freq %in% c('Not at all', 'Several days') ~ 'Less than half the days',
          anxiety_freq %in% c('More than half the days', 'Nearly every day') ~ 'More than half the days',
         TRUE
            ~ 'error catch'
        )
      ) %>%
      clean_names()%>%
      mutate(LGBTQ=case_match(select_characteristics, 
                                          "    Yes" ~"LGBTQ+ identifying",
                                          "    No" ~ "Not LGBTQ+ identifying",
                                          "    Other" ~ "LGBTQ+ identifying",
                                          "    Did not report" ~ "Did not report"))%>%
      group_by(LGBTQ, anxiety_grp)%>%
      mutate(sum_total=sum(as.numeric(total)))%>%
      select(anxiety_grp, LGBTQ, sum_total)%>%
      distinct()%>%
      group_by(LGBTQ)%>%
      mutate(share=prop.table(sum_total)) %>%
      mutate(week = week)
      
     
    df_anxiety <- rbind(df_anxiety, df_lgbtq_summ)
    
}
```

```{r}
df_anxiety_more<-df_anxiety%>%filter(anxiety_grp=='More than half the days')%>%drop_na()
static_line_chart(df_anxiety_more, x='week', y='share', fill='LGBTQ')

week_est<-df_anxiety_more |>
  e_charts(week) |>
  e_line(share) |>
  e_title("Anxiety Estimated by Week (Census Pulse weeks)")|>
  e_x_axis(week) |>
  e_legend(bottom=0)|>
  e_y_axis(
    formatter = e_axis_formatter("percent", digits = 0)
  )

week_est
```
### Depression Data download

```{r, echo=FALSE, message=FALSE, warning=FALSE}

#which weeks to summarize
week_range <- 34:57

sheet_name <- 'Seattle_Metro_Area'

df_depress<-data.frame()

for (week in week_range) {
  # have to assign which year each week was in to make the url
  if (week < 42) {
    year = '2021'
    #they changed the table names over time, ugh!!
    tbl <- list('health2b')
  }
  else if (week < 52)
  {
    year = '2022'
    # this is stupid
    if (week < 49) {
      tbl <- list('health2b')
    }
    else{
      tbl <- list('health2')
    }
  }
  else{
    year = '2023'
    tbl <- list('health2')
  }
  week_char <- as.character(week)

    url_end <-
      paste0(year,'/','wk',week_char,'/',tbl,
             '_week',week_char,'.xlsx')
    url <- paste0(url_start, url_end)
    file_end <- gsub('/', '_', url_end)
    dest_file = paste0(dest_file_loc, file_end)
    
    
    
    df <- read.xlsx(url, sheet = sheet_name, fillMergedCells = TRUE)
    df_row5 <- df %>% slice(5)
    df_row32_35<- df %>% slice(32:35)
    #df_row32_34<-df%>%slice(32:34)
    df_lgbtq <- bind_rows(df_row5, df_row32_35) %>% select(1:6)
    df_lgbtq <- df_lgbtq %>% row_to_names(row_number = 1)
    #rows 5 in the 25-30 position 32-34 position
    df_lgbtq[df_lgbtq=="-"] <- "0"
    
    df_lgbtq_summ <-
      df_lgbtq%>% pivot_longer(
        cols = c(
          'Not at all',
          'Several days',
          'More than half the days',
          'Nearly every day',
          'Did not report'
        ),
        names_to = 'depress_freq',
        values_to = 'total'
      ) %>%
      filter(depress_freq != 'Did not report') %>%
      mutate(
        depress_grp = case_when(
          depress_freq %in% c('Not at all', 'Several days') ~ 'Less than half the days',
          depress_freq %in% c('More than half the days', 'Nearly every day') ~ 'More than half the days',
         TRUE
            ~ 'error catch'
        )
      ) %>%
      clean_names()%>%
      mutate(LGBTQ=case_match(select_characteristics, 
                                          "    Yes" ~"LGBTQ+ identifying",
                                          "    No" ~ "Not LGBTQ+ identifying",
                                          "    Other" ~ "LGBTQ+ identifying",
                                          "    Did not report" ~ "Did not report"))%>%
      group_by(LGBTQ, depress_grp)%>%
      mutate(sum_total=sum(as.numeric(total)))%>%
      select(depress_grp, LGBTQ, sum_total)%>%
      distinct()%>%
      group_by(LGBTQ)%>%
      mutate(share=prop.table(sum_total)) %>%
      mutate(week = week)
    
    df_depress <- rbind(df_depress, df_lgbtq_summ)
    
}
```


```{r}
df_depress_more<-df_depress%>%filter(depress_grp=='More than half the days')%>%drop_na()
static_line_chart(df_depress_more, x='week', y='share', fill='LGBTQ')

```



```{r}
df_anxiety_more_56<-df_anxiety_more%>%filter(week =='56')%>%mutate(symptoms='anxiety')
df_depress_more_56<-df_depress_more%>%filter(week =='56')%>%mutate(symptoms='depression')
depress_anxiety<-rbind(df_anxiety_more_56, df_depress_more_56)%>%filter(LGBTQ!='Did not report')
```

```{r}
static_column_chart(depress_anxiety, x='symptoms',y='sum_total', fill= 'LGBTQ')

```
```{r}
df_anxiety_more_57<-df_anxiety_more%>%filter(week =='57')%>%mutate(symptoms='anxiety')
df_depress_more_57<-df_depress_more%>%filter(week =='57')%>%mutate(symptoms='depression')
depress_anxiety<-rbind(df_anxiety_more_57, df_depress_more_57)%>%filter(LGBTQ!='Did not report')
```

```{r}
static_column_chart(depress_anxiety, x='symptoms',y='share', fill= 'LGBTQ')

```


```{r}
df_anxiety_more_avg<-df_anxiety_more%>%group_by(LGBTQ)%>%summarize(mean_share=mean(share), mean_total=mean(sum_total))%>%
 mutate(symptoms='anxiety')
df_depress_more_avg<-df_depress_more%>%group_by(LGBTQ)%>%summarize(mean_share=mean(share), mean_total=mean(sum_total))%>%
 mutate(symptoms='depression')
depress_anxiety<-rbind(df_anxiety_more_avg, df_depress_more_avg)%>%filter%>%filter(LGBTQ!='Did not report')
```

```{r}
static_column_chart(depress_anxiety, x='symptoms',y='mean_share', fill= 'LGBTQ') +theme(text = element_text(size=20),
        axis.text.x = element_text(size=12))
```

```{r}
depress_anxiety<-depress_anxiety%>%mutate(rounded_total=round(mean_total, -3))
static_column_chart(depress_anxiety, x='symptoms',y='rounded_total', fill= 'LGBTQ')

```