---
title: "AAPI Trend"
author: "Brandon Wong"
output: html_document
---

```{r, include=FALSE}
source("aapi_trend2024.R")
```


```{r, include = FALSE, warning=FALSE}
df_pums_renter_all_race <- df_pums %>% filter(TEN=="Rented")

renter <- psrc_pums_count(df_pums_renter_aapi, group_vars=c("PRACE","RAC2P_aapi_group10","rent_pct_income_30"), rr=TRUE) %>% 
    add_row(psrc_pums_count(df_pums_renter_all_race, group_vars=c("PRACE", "rent_pct_income_30")) %>% 
               mutate(RAC2P_aapi_group10 = "Asian alone", .after="COUNTY")) %>% 
    filter(PRACE == "Asian alone") %>% 
    add_row(psrc_pums_count(df_pums, group_vars=c("rent_pct_income_30")) %>%
           mutate(RAC2P_aapi_group10 = "Region", .after="COUNTY"))


all_race_renter <- psrc_pums_count(df_pums_renter_all_race, group_vars=c("PRACE","rent_pct_income_30"), rr=TRUE) %>% 
      add_row(psrc_pums_count(df_pums, group_vars=c("rent_pct_income_30")) %>%
           mutate(PRACE = "Region", .after="COUNTY"))

```


## Plot 1

This plot displays Asian sub-groups who are cost burdened. This is defined by anyone paying 30% or more of their income for their rent expense.

```{r echo=FALSE, fig.height=10, fig.width=20, warning=FALSE}
# Making a Renter Cost Burden by Asian Sub-group stacked bar chart

cost_burdened <- renter %>% 
  filter(rent_pct_income_30 == "Greater than 30 percent") %>%
  select(RAC2P_aapi_group10, count, count_moe, share, share_moe, reliability) %>% 
  group_by(RAC2P_aapi_group10) %>%
  summarize(across(c(count, count_moe, share, share_moe), sum)) %>% # aggregates all numerical values based on race
  dplyr::mutate(perc = paste0(sprintf("%4.1f", share * 100), "%")) # adds a percentage column to the cost burdened share

# Version 3

ggplot(cost_burdened, aes(x=reorder(RAC2P_aapi_group10, share), y=share, fill=RAC2P_aapi_group10)) +
  geom_col()+
  geom_text(aes(y=share, label=scales::percent(share, accuracy = 0.1)), size = 7, hjust=-0.5)+
  geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe), width=0.2) +
  scale_y_continuous(labels=scales::percent)+
  scale_fill_manual(values = psrc_colors$pgnobgy_10)+
  coord_flip()+
  psrc_style() +
  labs(title = "Renter Cost Burden by APPI subgroups", caption = "data: AAPI Renter households by householder race", x="AAPI subgroups") +
  theme(axis.title = element_blank(), plot.title = element_text(size = 30), legend.position = "none", axis.text = element_text(size= 20), plot.caption = element_text(size = 20))
```
## Plot 2
```{r echo=FALSE, fig.height=10, fig.width=20, warning=FALSE}
cost_burdened_all_race <- all_race_renter %>% 
  filter(rent_pct_income_30 == "Greater than 30 percent") %>%
  select(PRACE, count, count_moe, share, share_moe, reliability) %>% 
  group_by(PRACE) %>%
  summarize(across(c(count, count_moe, share, share_moe), sum)) %>% # aggregates all numerical values based on race
  dplyr::mutate(perc = paste0(sprintf("%4.1f", share * 100), "%")) # adds a percentage column to the cost burdened share


ggplot(cost_burdened_all_race, aes(x=reorder(PRACE, share), y=share, fill=PRACE)) +
  geom_col()+
  geom_text(aes(y=share, label=scales::percent(share, accuracy = 0.1)), size = 7, hjust=-0.5)+
  geom_errorbar(aes(ymin=share-share_moe, ymax=share+share_moe), width=0.2) +
  scale_y_continuous(labels=scales::percent)+
  scale_fill_manual(values = psrc_colors$pgnobgy_10)+
  coord_flip() +
  psrc_style() +
  labs(title = "Renter Cost Burden by Race/Ethnicity", caption = "data: Renter households by householder race", x="All Races/Ethnicities") +
  theme(axis.title = element_blank(), plot.title = element_text(size = 30), legend.position = "none", axis.text = element_text(size= 20), plot.caption = element_text(size = 20))

```
## Plot 3
Most common jobs by in the region and the share of Asian populations within those jobs
filter for renter cost burden before their occupation

```{r, fig.height=15, fig.width=15, warning=FALSE}

library(data.table)
library(kableExtra)

  
job3_by_asian_alone <- psrc_pums_count(df_pums_p_aapi_renter_worker %>% filter(RAC2P_aapi_group10_household!="Native Hawaiian and Other Pacific Islander"), group_vars=c("SOCP3")) %>%
  arrange(desc(count))


job3_by_aapi_race <- psrc_pums_count(df_pums_p_aapi_renter_worker, group_vars=c("RAC2P_aapi_group10_household","SOCP3")) %>%
  mutate(PRACE="Asian alone", .before="RAC2P_aapi_group10_household") %>% 
  add_row(psrc_pums_count(df_pums_renter_all_race, group_vars=c("PRACE", "SOCP3")) %>%
            mutate(RAC2P_aapi_group10_household = "Asian alone", .after="COUNTY")) %>% 
  filter(PRACE == "Asian alone") %>% 
  add_row(psrc_pums_count(df_pums, group_vars=c("SOCP3")) %>%
           mutate(RAC2P_aapi_group10_household = "Region", .after="COUNTY"))

job_df <- job3_by_aapi_race %>% 
  group_by(RAC2P_aapi_group10_household) %>% 
  filter(SOCP3!="Total") %>%
  slice_max(count, n= 5) %>%
  mutate(occupation = str_c("Top_Occupation_", row_number())) %>% 
  spread(occupation, SOCP3) %>% 
  select(RAC2P_aapi_group10_household, Top_Occupation_1, Top_Occupation_2, Top_Occupation_3, Top_Occupation_4, Top_Occupation_5) %>%
  mutate(across(everything(), as.character)) %>% 
  replace(is.na(.), "") %>% 
  mutate(across(everything(), as.factor))
  

setDT(job_df)

job_df <- job_df[, lapply(.SD, paste0, collapse=""), by=RAC2P_aapi_group10_household]

kbl(job_df) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), html_font = "Poppins") %>%
  column_spec(c(2), background = psrc_colors$greens_inc[1]) %>% 
  column_spec(c(3), background = psrc_colors$purples_inc[1]) %>%
  column_spec(c(4), background = psrc_colors$greens_inc[1]) %>% 
  column_spec(c(5), background = psrc_colors$purples_inc[1]) %>% 
  column_spec(c(6), background = psrc_colors$greens_inc[1])

job3_region_top_5_edit <- job3_region %>%
  filter(SOCP3!="Total") %>%
  arrange(desc(share)) %>%
  top_n(5, share)


```

